// This file was autogenerated from schemas/1.05/Opc.Ua.NodeSet2.xml by async-opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua {
    pub(super) use opcua_nodes as nodes;
    pub(super) use opcua_nodes::{Event, EventField};
    pub(super) use opcua_types as types;
}
#[allow(unused)]
use opcua_types as types;
pub mod generated;
pub use generated::*;
